<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <WarningsAsErrors>Nullable</WarningsAsErrors>
        <Version>0.0.0</Version>
        <AssemblyName>SimplePBO-tool</AssemblyName>
        <PublishSingleFile>true</PublishSingleFile>
        <SelfContained>true</SelfContained>
        <RuntimeIdentifier>win-x64</RuntimeIdentifier>
        <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
        <ApplicationIcon>Assets\Multiplix.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="DZConfigTools.Core" Version="1.1.1" />
    </ItemGroup>

</Project>
